# Generated by Django 2.0.6 on 2018-06-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='dep',
            new_name='dept',
        ),
    ]
